apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-app
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app
    spec:
      containers:
      - image: lenisha/spring-jdbc-docker
        name: spring-jdbc-docker
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        command: ["/bin/sh","-c"]
        args: ["mkdir /mnt/azure/${MY_POD_NAME}; /opt/startup.sh"]  
        env:
          - name: SQL_URL
            value: jdbc:sqlserver://jogardn-sql-mi.9ec6e3297387.database.windows.net:1433;database=testpcc;responseBuffering=full;sendStringParametersAsUnicode=false;loginTimeout=30;
          - name: SQL_USER
            value: jogardn
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlpass
                key: SQL_PASS
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace   
          - name: CATALINA_TMPDIR
            value: /mnt/azure/${MY_POD_NAME}          
          - name: CATALINA_OPTS
            value: -XX:+UseParNewGC -Xmx5420m -Xms5420m -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
                   -XX:+UseConcMarkSweepGC -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl 
                   -XX:+ForceTimeHighResolution -Dnetworkaddress.cache.ttl=0 
                   -XX:+CMSParallelRemarkEnabled -Xrs -XX:+UseCMSInitiatingOccupancyOnly 
                   -XX:MaxNewSize=1536m -XX:MaxMetaspaceSize=1024M 
                   -Djavax.xml.soap.SOAPConnectionFactory=org.apache.axis.soap.SOAPConnectionFactoryImpl 
                   -XX:CMSInitiatingOccupancyFraction=68 -Xss1m -Djava.endorsed.dirs=${CATALINA_HOME}/endorsed 
                   -Dcatalina.home=${CATALINA_HOME} -XX:+CMSClassUnloadingEnabled -XX:NewSize=1536m -XX:+DisableExplicitGC 
                   -Desolutions.messaging.jms.system.name=${HOSTNAME} -XX:+CMSPermGenSweepingEnabled 
                   -Dderby.system.home=${CATALINA_HOME}/derbydb -server -Dsun.net.inetaddr.ttl=0 
                   -Djava.net.preferIPv4Stack=true -Djavax.xml.soap.SOAPFactory=org.apache.axis.soap.SOAPFactoryImpl 
                   -Djavax.xml.soap.MessageFactory=org.apache.axis.soap.MessageFactoryImpl -Dfile.encoding=UTF-8
          - name: JAVA_OPTS # CMSClassUnloadingEnabled -Djava.io.tmpdir=${CATALINA_BASE}/temp
            value: -DSQL_URL=${SQL_URL} -DSQL_USER=${SQL_USER} -DSQL_PASSWORD=${SQL_PASSWORD}   -Djava.awt.headless=true -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
        resources:
         limits:
           cpu: "5"
           memory: 8G
         requests:
           cpu: "3"
           memory: 6G
        readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /spring-jdbc-docker/create-user.html
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
        livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /spring-jdbc-docker/create-user.html
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 16 
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: azure    
        #- mountPath: "/opt/apache-tomcat-7.0.59/webapps/spring-jdbc-docker/WEB-INF/classes/logging.properties"
        #  name: log-config
        #  subpath: logging.properties  
      volumes:
      - name: azure #volume for jdbc logs
        azureFile:
          secretName: azure-secret-file
          shareName: aksfileshare
          readOnly: false    
      - name: log-config
        configMap: 
          name: log-config  
status: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
data:
  logging.properties: |-
    handlers=java.util.logging.FileHandler
    level= OFF
    java.util.logging.FileHandler.pattern=%t/jdbc%u.log
    java.util.logging.FileHandler.limit=500000
    java.util.logging.FileHandler.count=20
    java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
    java.util.logging.FileHandler.level=FINEST
    #java.util.logging.ConsoleHandler.level=FINEST
    com.microsoft.sqlserver.jdbc.level=FINEST
