apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-app
  name: java-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-app
  type: LoadBalancer
status:
  loadBalancer: {}
